version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: csarch_warehouse
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: products_warehouse
      MYSQL_USER: warehouse_user
      MYSQL_PASSWORD: warehouse_pass
    ports:
      - "3306:3306"
    volumes:
      - csarch_db:/var/lib/mysql

volumes:
  csarch_db: